(#96) Adds Optional SonarQube Step
chocolatey/Chocolatey.Cake.Recipe pull request #97
Opened 2023-01-27 16:18 UTC by JPRuskin

This adds build tasks for analysing and submitting results to a SonarQube instance.

It may not yet be suited to PR builds, as there are some additional settings involved, but it should suffice for scanning using the Community edition.

2023-02-17 09:56 UTC, JPRuskin commented
Did you have any thoughts on this, @gep13?

2023-02-17 09:57 UTC, gep13 commented
@JPRuskin I have not had a chance to review this PR yet, sorry.

2023-02-23 11:01 UTC, gep13 requested changes

2023-02-23 11:01 UTC, gep13 commented on Chocolatey.Cake.Recipe/Content/toolsettings.cake
> +        string sonarQubeTool = "#tool nuget:?package=MSBuild.SonarQube.Runner.Tool",
Does this tool work on all Operating Systems?  Or do we need to gate SonarQube execution to only run on Windows? i.e. what will happen when the tagged build runs on GitHub Actions for Mac and Linux?

2023-02-23 11:31 UTC, JPRuskin commented on Chocolatey.Cake.Recipe/Content/sonarqube.cake
> +        // Exclusions = ""
I had left them in as examples for future potential usage, but am happy to remove them

2023-02-23 11:33 UTC, JPRuskin commented on Chocolatey.Cake.Recipe/Content/parameters.cake
> +            if (BuildParameters.IsTagged && !BuildParameters.IsLocalBuild)
That's correct. Our license doesn't support multiple branches per project and Paul wanted to be able to produce reports on our tagged releases. We should change this if/when we upgrade to a license that allows for, e.g., PR build scanning before merge.

2023-02-23 11:40 UTC, gep13 commented on Chocolatey.Cake.Recipe/Content/parameters.cake
> +            if (BuildParameters.IsTagged && !BuildParameters.IsLocalBuild)
Sounds good.

2023-03-10 10:55 UTC, gep13 approved these changes
LGTM!

2023-03-10 10:55 UTC, merged